### ISSUE TITLE
how do i integrate this with my project(question)

### ISSUE THREAD

**Issue by jasan-s** [CodeLinkIO/Firebase-Image-Upload-React-Native#6]
Sorry, but its just unclear. how can i add firebase storage with my react native  ios and android using the lib?

**Comment by khacanh** [comment]
You just need to create a firebase project here https://console.firebase.google.com/?pli=1 

and then follow the instruction of this project to set that up. This project is not a lib, but a guide to use firebase.

**Comment by jasan-s** [comment]
I tried to basically test it functionality by following your guide and adding the demo.js component file. I keep getting error

>  undefined is not an object(evaluating 'RNFetchBlob.DocumentDIr')

**Comment by jasan-s** [comment]
weird now i there no error but when i click upload the app closes in simulator

**Comment by jasan-s** [comment]
GOt it working. Thanks spent few hours trying to get FireStack working. this helped
